title: "joeellis.la"
author: "Joe Ellis"
email: joe@joeellis.la
description: "Tech musings on all things Elixir, Ruby, and Javascript."
copyright: "joeellis.la &copy; 2017"
baseurl: ""
url: "http://joeellis.la"
logo: "/assets/images/avatar.png"
locale: "en_us"
timezone: "America/Chicago"

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed

twitter:
  username: notjoellis

social:
  name: Joe Ellis
  links:
    - https://twitter.com/notjoeellis
    - https://github.com/joeellis
