# Site settings
title: "joeellis.la"
email: joe@joeellis.la
description: "joeellis.la &copy; 2017"
baseurl: ""
url: "http://joeellis.la"

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge

gems: [jekyll-paginate]

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
